apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agentic-ai
  namespace: argocd
spec:
  destination:
    namespace: agentic-ai
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/mejavsh/argocd-gitops-agentic-ai
    targetRevision: main
    path: kustomize/dev   # choose dev/prod
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

